name: Distribution

on:
  push:
    branches:
      - '!*'
    tags:
      - '*'

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/distributions/com.elovirta.pdf.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
